source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

#link_with 'Tests', 'TestsTests'
#pod "Rosetta", :path => "../"

target 'ios' do
  platform :ios, '8.0'
  pod 'Rosetta', :path => "../"
end

target 'iosTests' do
  platform :ios, '8.0'
  pod 'Rosetta', :path => "../"
end

target 'osx' do
  platform :osx, '10.10'
  pod 'Rosetta', :path => "../"
end

target 'osxTests' do
  platform :osx, '10.10'
  pod 'Rosetta', :path => "../"
end
